### ISSUE TITLE
项目部署报错

### ISSUE THREAD

**Issue by lysnoter** [Carrotzpc/ant-koa-demo#1]
我在执行cnpm install的时候报错.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\b
in\npm-cli.js" "install"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

**Comment by Carrotzpc** [comment]
@lysnoter 看上面的报错信息，应该是没安装 `git`导致的

```
npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
```

**Comment by lysnoter** [comment]
@Carrotzpc 抱歉我是新手，请问这个GIT是指什么？

**Comment by Carrotzpc** [comment]
`git`是一种项目版本控制工具，类似于 `svn`，`git`教程参考 [http://rogerdudler.github.io/git-guide/index.zh.html](http://rogerdudler.github.io/git-guide/index.zh.html)

**Comment by lysnoter** [comment]
@Carrotzpc 非常感谢!
